version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      day: monday
      interval: weekly
      time: "08:30"
      timezone: Europe/Paris
    commit-message:
      prefix: "ci"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      day: monday
      interval: weekly
      time: "08:30"
      timezone: Europe/Paris
    commit-message:
      prefix: "deps"
      include: "scope"
